apiVersion: v1
kind: Service
metadata:
  name:  todo-server
spec:
  clusterIP: None
ports:
- name:  grpc
  port:  8000
  protocol: TCP
  selector:
    app: todo-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
  labels: 
    app: todo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
      - name: todo-server
        image:  registry/user/image
        ports:
        - name:  grpc
          port:  8000
          protocol: TCP
